//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HoaDonBan
    {
        [Key]
        public int MaHD { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaKH { get; set; }

        [DisplayName("Ngày bán")]
        [DataType(DataType.DateTime, ErrorMessage = "Phải là {0}")]
        public Nullable<System.DateTime> NgayBan { get; set; }

        [DisplayName("Số lượng")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} phải lớn hơn 0")]
        public Nullable<int> SoLuong { get; set; }

        [ForeignKey("MaKH")]   
        public virtual KhachHang KhachHang { get; set; }

        [ForeignKey("MaSach")]
        public virtual Sach Sach { get; set; }
    }
}
