//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }

        [Key]   
        public int MaSach { get; set; }

        [DisplayName("Tên sách")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "{0} có độ dài từ {2} đến {1} ký tự")]
        [Required(ErrorMessage = "Phải có {0}")]
        public string TenSach { get; set; }

        [DisplayName("Thể loại")]
        [Required(ErrorMessage = "Phải có {0}")]
        [StringLength(30, ErrorMessage = "{0} có độ dài {1} ký tự")]
        public string TheLoai { get; set; }

        [DisplayName("Đơn giá")]
        [Required(ErrorMessage = "Phải có {0}")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} phải lớn hơn 0")]
        public Nullable<decimal> DonGia { get; set; }

        [DisplayName("Số lượng tồn")]
        [Required(ErrorMessage = "Phải có {0}")]
        [Range(1, int.MaxValue, ErrorMessage = "{0} phải lớn hơn hoặc bằng {1}")]
        public Nullable<int> SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
